export const data = {
    "pagination": {
        "next": {
            "available": true,
            "label": "Next",
            "page": 2
        },
        "previous": {
            "available": false,
            "label": "Previous",
            "page": -1
        },
        "pageSize": 10,
        "currentPage": 1,
        "totalCount": 383,
        "results": [
            {
                "enable": true,
                "page": 1,
                "currentPage": true,
                "type": "page"
            },
            {
                "enable": true,
                "page": 2,
                "currentPage": false,
                "type": "page"
            },
            {
                "enable": true,
                "page": 3,
                "currentPage": false,
                "type": "page"
            },
            {
                "enable": true,
                "page": -1,
                "currentPage": false,
                "type": "dots"
            },
            {
                "enable": true,
                "page": 39,
                "currentPage": false,
                "type": "page"
            }
        ]
    },
    "orders": [
        {
            "atgOrderID": "o39550472",
            "shipInfoMsg": null,
            "orderId": "YD44021",
            "orderRelatedDocuments": null,
            "otherCharges": 0,
            "totalMsg": "Calculated at the time of invoicing.",
            "source": "Yes",
            "subTotal": 0,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "54004179",
            "orderPlacedDate": "10-08-2023",
            "total": 0,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "14200 E MONCRIEFF PLACE",
                    "city": "AURORA",
                    "address1": "BEACON BUILDING PRODUCTS",
                    "postalCode": "80011-1647",
                    "state": "CO"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "P"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "723e866f-bb5a-498b-a4cf-3997becdbb93",
            "sellingBranch": "300",
            "onHold": true,
            "specialInstruction": "[\"54004179\"]",
            "displayTotalMsg": true,
            "showDropDown": null,
            "tax": 0,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "llKFn_t9kNWoNkYnggvLJf9gltCKmN7XG6skg_W2rz8=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o39550470",
            "shipInfoMsg": null,
            "orderId": "YD44020",
            "orderRelatedDocuments": null,
            "otherCharges": 0,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 119.12,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "TEST UPDATE",
            "orderPlacedDate": "10-08-2023",
            "total": 129.24,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "14200 E MONCRIEFF PLACE",
                    "city": "AURORA",
                    "address1": "BEACON BUILDING PRODUCTS",
                    "postalCode": "80011-1647",
                    "state": "CO"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "P"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": true,
            "specialInstruction": "[\"This is test order.Please cancel Pick u p in ROOF DEPOT MOUNTAIN 4795 FOREST ST . CO, DENVER 80216 on a day and time to  be determined. Order placed by UAT api  API test, email: bdd_approver@aaxischi na.com.\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 10.12,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "dy6AY9uz7SyJPasgkv50W9uzc0pjl97t2A_JU87PSO4=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o39540406",
            "shipInfoMsg": null,
            "orderId": "YD44019",
            "orderRelatedDocuments": null,
            "otherCharges": 0,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 119.12,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "TEST UPDATE",
            "orderPlacedDate": "10-08-2023",
            "total": 129.24,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "14200 E MONCRIEFF PLACE",
                    "city": "AURORA",
                    "address1": "BEACON BUILDING PRODUCTS",
                    "postalCode": "80011-1647",
                    "state": "CO"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "P"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": true,
            "specialInstruction": "[\"This is test order.Please cancel Pick u p in ROOF DEPOT MOUNTAIN 4795 FOREST ST . CO, DENVER 80216 on a day and time to  be determined. Order placed by UAT api  API test, email: bdd_approver@aaxischi na.com.\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 10.12,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "80b4dbzoFoupEyown5s8aIeJUG45CEWHHzSRXMMKs7w=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o98231060",
            "shipInfoMsg": null,
            "orderId": "NB97423",
            "orderRelatedDocuments": null,
            "otherCharges": 0,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 357.36,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "TEST UPDATE",
            "orderPlacedDate": "08-18-2023",
            "total": 387.73,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "14200 E MONCRIEFF PLACE",
                    "city": "AURORA",
                    "address1": "BEACON BUILDING PRODUCTS",
                    "postalCode": "80011-1647",
                    "state": "CO"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "P"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": true,
            "specialInstruction": "[\"This is test order.Please cancel Pick u p in ROOF DEPOT MOUNTAIN 4795 FOREST ST . CO, DENVER 80216 on a day and time to  be determined. Order placed by UAT api  API test, email: bdd_apiuser@aaxischin a.com.\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 30.37,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "sappRJk73KdQXmvq6ZdANLpbHf2Fkeokq-4b0XFz5x4=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o98217339",
            "shipInfoMsg": null,
            "orderId": "NB75245",
            "orderRelatedDocuments": null,
            "otherCharges": 125,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 53.5,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "BDD_PO",
            "orderPlacedDate": "08-17-2023",
            "total": 188.32,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "TEST()TEST()[]/<AAA%00>",
                    "city": "KAUKAUNATEST()[]/<AAA%00>",
                    "address1": "860 E LINE RDTEST()[]/<AAA%00>",
                    "postalCode": "54130",
                    "state": "WI"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "O"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": true,
            "specialInstruction": "[\"This is a testing order, please cancel Ship to 860 E Line Rdtest()[]/\\u003caaa%00\\u003e test()test()[]/\\u003caaa%00\\u003e WI, Kaukaunates t()[]/\\u003caaa%00\\u003e 54130 on a day and time to be determined. Order placed by BDD U ser2 AAXIS, email: bdduser2@aaxischin\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 9.82,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "6OobRldQHgzFc9zE0F4b8lcerZi1ETo80Cam2A1-wtY=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o98231251",
            "shipInfoMsg": null,
            "orderId": "NB75205",
            "orderRelatedDocuments": null,
            "otherCharges": 125,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 53.5,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "BDD_PO",
            "orderPlacedDate": "08-17-2023",
            "total": 188.32,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "TEST()TEST()[]/<AAA%00>",
                    "city": "KAUKAUNATEST()[]/<AAA%00>",
                    "address1": "860 E LINE RDTEST()[]/<AAA%00>",
                    "postalCode": "54130",
                    "state": "WI"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "O"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": true,
            "specialInstruction": "[\"This is a testing order, please cancel Ship to 860 E Line Rdtest()[]/\\u003caaa%00\\u003e test()test()[]/\\u003caaa%00\\u003e WI, Kaukaunates t()[]/\\u003caaa%00\\u003e 54130 on a day and time to be determined. Order placed by Norma l2 AAXIS, email: bddnormal2@aaxischin\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 9.82,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "H6SLyYSYBQFkx5kB6ciR1PoZFIuSedPIq74Hmp1aL54=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o98217229",
            "shipInfoMsg": null,
            "orderId": "NB75116",
            "orderRelatedDocuments": null,
            "otherCharges": 125,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 53.5,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "BDD_PO",
            "orderPlacedDate": "08-17-2023",
            "total": 188.32,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "TEST()TEST()[]/<AAA%00>",
                    "city": "KAUKAUNATEST()[]/<AAA%00>",
                    "address1": "860 E LINE RDTEST()[]/<AAA%00>",
                    "postalCode": "54130",
                    "state": "WI"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "O"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": true,
            "specialInstruction": "[\"This is a testing order, please cancel Ship to 860 E Line Rdtest()[]/\\u003caaa%00\\u003e test()test()[]/\\u003caaa%00\\u003e WI, Kaukaunates t()[]/\\u003caaa%00\\u003e 54130 on a day and time to be determined. Order placed by Norma l2 AAXIS, email: bddnormal2@aaxischin\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 9.82,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "GaLFM_ceZZLJDKtZrHw4JDKt1hWWUjd1kriCStXRRus=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o98169457",
            "shipInfoMsg": null,
            "orderId": "NB75114",
            "orderRelatedDocuments": null,
            "otherCharges": 0,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 53.5,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "BDD_PO",
            "orderPlacedDate": "08-17-2023",
            "total": 58.05,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "14200 E MONCRIEFF PLACE",
                    "city": "AURORA",
                    "address1": "BEACON BUILDING PRODUCTS",
                    "postalCode": "80011-1647",
                    "state": "CO"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "P"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": false,
            "specialInstruction": "[\"This is a testing order, please cancel Pick up in MOUNTAIN REGION CORP 14200 E  MONCRIEFF PLACE CO, AURORA 80011-1647 on 08-21-2023 9AM. Order placed by Norm al5 AAXIS, email: bddnormal5@aaxischina .com.\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 4.55,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "NKRqb1Kq4L1wiD43XMCeDwU-rnhYXQj9xqek1Ho4EEA=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o98000582",
            "shipInfoMsg": null,
            "orderId": "NB75112",
            "orderRelatedDocuments": null,
            "otherCharges": 0,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 53.5,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "BDD_PO",
            "orderPlacedDate": "08-17-2023",
            "total": 58.05,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "14200 E MONCRIEFF PLACE",
                    "city": "AURORA",
                    "address1": "BEACON BUILDING PRODUCTS",
                    "postalCode": "80011-1647",
                    "state": "CO"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "P"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": false,
            "specialInstruction": "[\"This is a testing order, please cancel Pick up in BEACON BUILDING PRODUCTS 142 00 E MONCRIEFF PLACE CO, AURORA 80011-1 647 on 08-21-2023 9AM. Order placed by BDD User6 AAXIS, email: bdduser6@aaxisc hina.com.\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 4.55,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "1GPt6r9Pd1gl3YZ_oMNJBgbG90GOyi8mvMI6YoJ3-s4=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        },
        {
            "atgOrderID": "o98217166",
            "shipInfoMsg": null,
            "orderId": "NB75069",
            "orderRelatedDocuments": null,
            "otherCharges": 125,
            "totalMsg": null,
            "source": "Yes",
            "subTotal": 53.5,
            "taxNull": false,
            "creditHold": "",
            "purchaseOrderNo": "BDD_PO",
            "orderPlacedDate": "08-17-2023",
            "total": 188.32,
            "shipping": {
                "shippingBranch": "300",
                "address": {
                    "address3": "",
                    "address2": "TEST()TEST()[]/<AAA%00>",
                    "city": "KAUKAUNATEST()[]/<AAA%00>",
                    "address1": "860 E LINE RDTEST()[]/<AAA%00>",
                    "postalCode": "54130",
                    "state": "WI"
                },
                "shippingBranchDisplayName": "DENVER HUB BRANCH",
                "shippingMethod": "O"
            },
            "inStore": "Yes",
            "showShipTips": null,
            "orderStatusValue": "Pending",
            "otherChargesNull": false,
            "UUID": "",
            "sellingBranch": "300",
            "onHold": true,
            "specialInstruction": "[\"This is a testing order, please cancel Ship to 860 E Line Rdtest()[]/\\u003caaa%00\\u003e test()test()[]/\\u003caaa%00\\u003e WI, Kaukaunates t()[]/\\u003caaa%00\\u003e 54130 on a day and time to be determined. Order placed by BDD U ser1 AAXIS, email: bdduser1@aaxischin\"]",
            "displayTotalMsg": null,
            "showDropDown": null,
            "tax": 9.82,
            "accountId": "280381",
            "shipTipsMsg": null,
            "orderStatusCode": "N",
            "shipContentMsg": null,
            "accountToken": "flyC9ZkVqWx2Ixrn62tkakusmuM3xDCaWX-7NxUwmaY=",
            "job": {
                "jobName": "SHOP ACCOUNT",
                "jobLocationAddress2": null,
                "jobLocationAddress3": null,
                "jobLocationZipCode": null,
                "jobLocationCity": null,
                "jobLocationAddress1": null,
                "customerName": null,
                "jobNumber": "SHOP",
                "customerTelephoneNumber": null,
                "jobLocationState": null
            },
            "subTotalNull": false,
            "showDeliveryNotification": null,
            "totalNull": false
        }
    ]
}